name: api_notas
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  http: ^1.6.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
